# Generated by Django 4.0.6 on 2022-07-15 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0001_initial'),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='client',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='website.client'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='contractor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='website.company'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.employee'),
        ),
    ]
