# Generated by Django 4.0.6 on 2022-07-15 10:33

import address.models
from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0003_auto_20200830_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('middle_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=50)),
                ('State', localflavor.us.models.USStateField(max_length=2)),
                ('Zip Code', localflavor.us.models.USPostalCodeField(blank=True, max_length=2, null=True)),
                ('gender', models.CharField(max_length=7)),
                ('social_security_number', localflavor.us.models.USSocialSecurityNumberField(blank=True, max_length=11, null=True)),
                ('employment_type', models.CharField(choices=[('W-2', 'Employee'), ('1099', 'Independent Contractor'), ('C2C', 'Corp-to-Corp')], default='1099', max_length=4)),
                ('Street Address', address.models.AddressField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='address.address')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('main_line', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('website_url', models.URLField(blank=True)),
                ('headquarters_address', address.models.AddressField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='address.address')),
            ],
            options={
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=500)),
                ('State', localflavor.us.models.USStateField(blank=True, max_length=2)),
                ('Zip Code', localflavor.us.models.USPostalCodeField(blank=True, max_length=2, null=True)),
                ('extension_line', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('cell_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('personal_profile', models.URLField(blank=True)),
                ('Street Address', address.models.AddressField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='address.address')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.company')),
            ],
        ),
    ]
